name: CI - Node.js App

on:
  push:
    branches:
      - main
      - tes-devops
  pull_request:
    branches:
      - main
      - tes-devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Masuk ke folder frontend
      - name: Change directory to frontend
        run: cd frontend

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install Vitest
        run: npm install -D vitest
        working-directory: ./frontend

      # Run tests
      - name: Run tests
        run: npm test
        working-directory: ./frontend
